//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoPartialView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string Phone1 { get; set; }
        public string phone2 { get; set; }
        public string ContactName { get; set; }
        public string City { get; set; }
    }
}
